/*
 * can_bus.h
 *
 *  Created on: Apr 30, 2025
 *      Author: rolf
 */

#ifndef INC_CAN_BUS_H_
#define INC_CAN_BUS_H_

#include "stm32g4xx_hal.h"

// External FDCAN handle (generated by CubeMX)
extern FDCAN_HandleTypeDef hfdcan1;

// Public functions
void CAN_Init(void);
HAL_StatusTypeDef CAN_Send(uint32_t id, uint8_t *data, uint8_t len);
HAL_StatusTypeDef CAN_Receive(uint32_t *id, uint8_t *data, uint8_t *len);


#endif /* INC_CAN_BUS_H_ */
